name: Convert CSV to HTML

on:
  push:
    paths:
      - 'doc/identifiers/*.csv'
    branches:
      - '**'
  workflow_dispatch:  

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref_name }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: List CSV files
      run: |
        echo "Listing CSV files in the /doc/identifiers/ directory"
        ls -l doc/identifiers/*.csv || echo "No CSV files found in /doc/identifiers/"

    - name: Get branch name
      id: branch_name
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        echo "Branch name is $BRANCH_NAME"
        echo "::set-output name=branch::$BRANCH_NAME"

    - name: Convert CSV to HTML
      run: |
        branch_name="${{ steps.branch_name.outputs.branch }}"
        output_dir="gitBranches/${branch_name}/identifiers"
        mkdir -p "$output_dir"
        python .github/build/convert_csv_to_html.py "$output_dir"

    - name: Checkout gitActions branch
      uses: actions/checkout@v2
      with:
        ref: gitActions
        path: gitActions

    - name: Clean up old directories in gitActions
      run: |
        branch_name=${{ steps.branch_name.outputs.branch }}
        echo "Cleaning up old directories in gitBranches/$branch_name/identifiers in gitActions branch."

        rm -rf gitActions/gitBranches/$branch_name/identifiers

    - name: Copy generated files to gitActions branch
      run: |
        branch_name=${{ steps.branch_name.outputs.branch }}
        echo "Copying generated HTML files to gitBranches/$branch_name/identifiers in gitActions branch."

        # Ensure the directories exist in gitActions
        mkdir -p gitActions/gitBranches/$branch_name/identifiers

        # Copy the HTML files to the gitActions branch folder
        cp -r ./gitBranches/$branch_name/identifiers/* gitActions/gitBranches/$branch_name/identifiers

    - name: Commit and push changes to gitActions branch
      working-directory: gitActions
      run: |
        branch_name=${{ steps.branch_name.outputs.branch }}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "gitBranches/$branch_name/identifiers/"
        git diff --staged --quiet || git commit -m "Automated conversion of CSV to HTML for $branch_name"
        git diff --staged --quiet || git push origin gitActions
